FROM mcr.microsoft.com/vscode/devcontainers/python:3.10

RUN python -m pip install --upgrade pip && \
    python -m pip install numpy && \
    python -m pip install scipy && \
    python -m pip install matplotlib && \
    python -m pip install msgpack-rpc-python && \
    python -m pip install pandas && \
    python -m pip install keyboard && \
    python -m pip install airsim